# Generated by Django 5.1.2 on 2024-11-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="categoria",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="livro",
            name="isbn",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="livro",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
